[package]
name = "cloudgrabber"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
tokio = { version = "1", features = ["full"] }
git2 = "0.13.20"
anyhow = "1.0"
dirs = "3.0"

